
local VisualLibrary = VisualLibrary

local baseGameOptions = {}

-- BEGIN Generated Entries: output_0_CharacterCreationSharedVisuals_from_CharacterCreationSharedVisuals.lua

baseGameOptions["06d99409-955b-474b-91ed-6fb8a69e3d3d"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "No Beard"                      , IntendedRace = "None"      , Description = "", }
baseGameOptions["546f55e1-efb7-46d0-b29e-490278a53274"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Jawclinger"                    , IntendedRace = "None"      , Description = "", }
baseGameOptions["76441c78-7d56-420c-b143-f28b89b3f2d6"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Groomed Rascal"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["6ff9872b-3884-4487-a22a-3e968e1d02c9"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Charming Devil"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["aee6d79b-3585-4ee8-9fc5-1abe2e37c23d"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Mineshaft"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["ebf9e69a-f59c-4bea-93a8-be9004e13ca8"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Plain Goatee"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["f78287d8-6dea-4106-acc7-0560f6afdb87"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Concise Statement"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["cdb8314c-2d93-475c-a7a2-c2459e9640cd"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Roguish"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["95551c8a-3a15-4b2a-92da-ca25fd2175c6"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Chin Grove"                    , IntendedRace = "None"      , Description = "", }
baseGameOptions["4044e46f-2fcf-4f2f-b829-4107d26ac894"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Judicious"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["fc0f51d7-f518-4b90-a34d-2e4c9712bb44"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Rambling Obscenity"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["ad84ec71-e323-4bf0-8cc5-ff3babd62678"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Charlatan's Goatee"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["6f786ec5-06d0-41ea-aa8e-481a1cfb348d"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Pointed Retort"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["59de03d7-79a3-4115-ae73-b5f7cee3f363"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Fireforge Tassels"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["7d890dbd-8e48-4aa1-820d-2e82724341f4"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Spiffing Twiddler"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["2e6a244a-487f-4b8f-b07c-320944972eac"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Tickler"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["cd6485e9-51ae-44be-a09c-5325ba262290"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Pomposity"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["2ada3e1a-b0da-49e4-9701-a818056120dd"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Opera Attendee"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["ccdae125-6177-41f5-b8d7-cd714763eb07"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Glorious Muttonchops"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["648360f5-ea8f-4398-8738-e3e6a5bcf989"] = { SlotName = "Beard"         , BodyType = "None" , BodyShape = "None"  , Name = "Facial Hair 19"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["76df94f8-bb0e-4fc7-9ce5-a666f2f47a06"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear Fang R"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["2f48a311-325a-4303-83cd-121df9ca6c3b"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear Claw R"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["f8f94018-6b34-43ed-a3fd-31392864fba0"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear Fang L"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["f91fcab5-e4ab-40b9-9e45-d73913288ace"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear Claw L"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["923cab0e-9ba4-4bc9-9fbf-c4c661dd6f43"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear Brow R"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["e8df0250-46f9-405c-9fa6-55b1a9a8119e"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB_Bear Brow R"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["5637952a-dd79-4803-bb91-732606917c7d"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear SeptRing"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["3458671f-d345-47b7-aed9-33acaa7d9140"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear HelixrRing L"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["6e9e5bb1-68b1-41a2-b22d-e117151abec6"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear Stub R"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["420b14a9-ec23-47a1-9109-0b6c9ded7f5e"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Bear Stub R"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["7a18be45-1186-4753-99b8-86700df3b2d6"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear Brow L"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["8da18476-b4ab-4812-97c5-583bdc8b56a5"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Bear Brow L"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["4564dfa9-d818-45e6-87ac-744ceea4abb7"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Bear Brow R"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["e5d21d17-52e3-4c0b-a791-d6bb513810dc"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear Pad Bridge R"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["9f144714-747f-4a8d-b9c8-72da46813606"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear Stub L"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["c14b08d1-b61f-459f-9637-69f80e9f67a8"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Bear Stub L"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["488764f9-d69a-4c70-a837-aa9e15059410"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear Pad Bridge L"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["0f5ad7fc-9c12-417d-8a5a-74cfa402d08a"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Bear HelixRing R"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["a32294c6-6ff0-4267-85de-ef682ad4f9dd"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Bear Pad Bridge R"         , IntendedRace = "None"      , Description = "", }
baseGameOptions["f69f73a2-e2ec-481e-93d2-47ca57c89933"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Bear HelixRing L"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["5c00df63-b5d5-4b9d-970f-0178185e9c89"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Bear HelixRing R"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["a44f8acc-5730-43d5-ad05-6620b4cbaefb"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Bear HelixRing R_B"        , IntendedRace = "None"      , Description = "", }
baseGameOptions["0c50da5c-4d98-44cd-bd7b-dad6fb56e302"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Eagle Brow Ring L"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["2bbfc373-6f7a-41d6-8195-49799e1fca5b"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Eagle Nose Ring L"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["fbf55812-f344-4e15-b264-20c5762eacc8"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Eagle Nose Ring Lowlip A L", IntendedRace = "None"      , Description = "", }
baseGameOptions["1c0f7164-3eef-4832-a59e-4109d68167a6"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Eagle Nose Ring Nostril A L", IntendedRace = "None"      , Description = "", }
baseGameOptions["93a97c0a-10ba-4f47-af74-48a3513edf97"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Eagle Nose Ring  Lowlip A R", IntendedRace = "None"      , Description = "", }
baseGameOptions["f32e763d-d06a-4446-a0be-4f8c6e59c9ef"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Eagle Talon L"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["a98c28e5-7fca-4970-a72d-a14de5569a10"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Eagle Wing L"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["035ae250-e1d3-4455-9ab4-6251ff8ea9a8"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Eagle Sept Ring M"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["80fe963f-945f-42fc-9c89-b0e237998b8f"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Eagle Sept Ring Nostril A L", IntendedRace = "None"      , Description = "", }
baseGameOptions["2ab1b724-e135-4201-84b5-f10718aaf49c"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Eagle Brow Ring R"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["d65b5840-af18-4d2e-86ac-667151b504b0"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Eagle Talon R"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["6d243492-db25-4858-8a92-2bd9301ad7d2"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Eagle Wing R"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["e3bb1ffa-f365-4f7b-9493-1853e02d52a0"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Eagle Ring L"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["9b14f767-00d0-45b7-b909-76dfc26fbd45"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Eagle Nose Ring R"         , IntendedRace = "None"      , Description = "", }
baseGameOptions["a4cf6241-15a1-4471-b8d7-e033b3ef0821"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Eagle Wing R"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["1fe8b549-bb4e-47c9-b02b-09273bb67304"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Eagle Wing L"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["2cbb21f1-512a-42db-ad2d-48fb5b94da12"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Eagle Stud"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["52889bce-ad33-4626-8ce6-c6122a13ae29"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Eagle Stud B L"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["24a99cc2-6845-41ea-a7e7-5e0c2ece1dc8"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Elk Antlers L"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["8fdbf362-c8ef-44ea-b476-eac96e4b0d88"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Elk Antlers R"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["e6f20c91-cfe6-40b0-a5c9-6ee8805580e3"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Elk Carving L"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["c984b9b9-c483-4413-90e9-f5820243c7d5"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Elk Carving R"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["275b8616-00f5-4312-b91d-fee22ccc9bc8"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Elk Carving R"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["4175c6b6-9bc0-4ada-8d41-5cdd16048603"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Elk Carving Uplip C R"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["a09e8744-9150-48d3-8ca0-9c66a74926fc"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Elk Carving Uplip D R"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["99c4ded0-f158-479e-9d64-fc98a4614abf"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Elk Carving Uplip C L"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["0538178a-468b-4fc8-9be2-da65180f01b1"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Elk Carving Uplip D L"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["0c52811a-a5de-49c5-b36d-5d27da5b8d09"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Elk Ring L"                    , IntendedRace = "None"      , Description = "", }
baseGameOptions["27e94952-9ea8-4954-b2f6-7ac5b2565e9a"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Elk Ring R"                    , IntendedRace = "None"      , Description = "", }
baseGameOptions["39eca6d3-7dad-4b56-a77b-dc6618e62f84"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Elk Sept Ring M"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["18b289b9-ec9e-4812-a5d6-329a941ae4db"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Elk Sphere L"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["4bf1110e-adfc-4ccf-ad5a-788fc0958cdf"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Elk Sphere R"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["ac3f4b09-ee11-445b-afe0-4ecfc86dbfda"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Elk Antlers Mouth L"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["7ebdd137-297c-4afa-a5e5-fd21d49c508a"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Elk Antlers Mouth R"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["00aecc81-75be-4ec2-8b05-197e8dd2e266"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Elk Antlers Brow L"        , IntendedRace = "None"      , Description = "", }
baseGameOptions["4f060223-bcee-4a33-8a05-ad0dd40b6ecf"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Elk Antlers Brow R"        , IntendedRace = "None"      , Description = "", }
baseGameOptions["6b6a39fc-87bc-47e7-995c-80b3015b1d70"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Elk Ring L"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["22eb7430-23cc-4523-8b86-5560d82f6f58"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Elk Ring Brow A R"         , IntendedRace = "None"      , Description = "", }
baseGameOptions["91d66a20-6421-4385-b445-f19e3285b7fd"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Tiger Gem L"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["f066fd0a-051e-4cd9-83b8-05cbc1ef4bfe"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Tiger Gem R"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["5b3d0097-b30b-4a60-bc09-97c1bcf215bd"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Tiger Nail L"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["36cc29e9-6aba-460c-bc64-f78004c644b7"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Tiger Nail R"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["a7804e00-efdc-4871-95a7-66e6ae2ea62d"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Tiger Spike L"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["f615a68b-3fe3-4d21-a0ae-544876578f25"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Tiger Spike R"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["6b50f00d-ab88-40de-bbae-0c870ef96628"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Tiger SpikeBig L"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["c2645a3e-516b-4ceb-8cd3-c303e86f8cff"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Tiger SpikeBig R"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["131e8638-122a-43d5-bea0-d8b22892b477"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Tiger Brow L"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["1ca81246-d35a-4fe0-ad60-23f0552accea"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Tiger Brow R"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["866b969d-7316-4f77-8f5a-23c1ed212bba"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Tiger Lowlip B L"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["4fdd05aa-e101-43df-88e7-39b86f28e50d"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Tiger Lowlip C L"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["b0a70063-9d10-4656-84bc-a464fa1409ab"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Tiger Lowlip B R"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["4d79e490-40a6-45fe-a771-7d73c22e4210"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Tiger Lowlip C R"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["d0075293-ef37-4eae-93c9-f948df2239b2"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Tiger Nostril R"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["bfb77733-fcfc-440c-84aa-c9bdf0ef9acd"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Tiger Ring L"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["825b3bc9-1302-45da-bdbe-aa6de45cbafa"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Tiger Uplip R"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["d166cd5e-175a-4f60-92c5-eca676491b56"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Tiger Uplip L"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["863c3233-18fa-4891-a159-ae9e00b9fbe3"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Tiger Stud L"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["20cd941c-8f09-4e53-8a31-8457e5edd22b"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Wolf Branch L"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["dc5d9502-9296-4c67-b01a-b2a772fe6b19"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Wolf Branch R"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["cd8be905-03f5-4e0f-a4e6-de68ae6f714e"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Wolf EarringLarge L"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["1c62a50a-5871-43a5-afac-460e48597404"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Wolf EarringLarge R"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["10c857a3-a99c-4bf3-9530-11f9ff5f6051"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Wolf EarringHelixA L"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["fc596209-7264-4e43-b4fc-4718e7a2c14a"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Wolf EarringHelixB L"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["ccb0dd23-1c70-4f7d-9131-613458338c55"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Wolf EarringHelixA R"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["c865951b-cd3f-49d3-87d4-cdb6327fe482"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Wolf EarringHelixB R"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["4d1ffd7d-e712-4f72-b058-5fb7b692e1f0"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Wolf SeptRing"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["98c958a9-efca-4129-8d91-6b963aee979a"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Wolf Sphere L"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["7f3360fb-964e-4139-9f65-9ca4ad40645d"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Wolf Lowlip D R"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["7defc0f0-f507-4e48-bdf5-85a29abf4b25"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Wolf Lowlip C R"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["48301130-b6f9-43b0-aa02-8ba75a0cec70"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Wolf Brow B R"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["6945b960-e04b-4998-886e-c48840021f11"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Wolf Ring L"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["d7985693-b7aa-47f1-9aaf-3b257b350b72"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Wolf Stud B L"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["ddad9354-bc90-462e-a081-180aa8ada9f2"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Wolf Stud Bridge A  R"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["6283b3df-da31-4726-9e27-e810b3847629"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Wolf Stud Uplip D L"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["d3b6144f-562f-44e8-9172-acccd556ed64"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Wolf Stud Uplip C L"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["73f8dd59-6094-4f88-987d-2642a24886a0"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Wolf Stud Uplip D R"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["1db12eb4-bc89-46c4-9313-8a7e84bb3216"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Wolf Stud Uplip C R"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["1fa9c750-77a9-47fa-b792-9b532a58981d"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Wolf Stud Lowlip D L"      , IntendedRace = "None"      , Description = "", }
baseGameOptions["528dd020-5a5a-470d-aa56-1e1f7df7f2f8"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Wolf Stud Lowlip C L"      , IntendedRace = "None"      , Description = "", }
baseGameOptions["2815ff06-f464-4d2f-8450-a2fdabd38ca1"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Wolf Sphere R"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["f138a651-46b6-4fb7-a7cd-ce44bd15fb07"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Ortheus BrowRing L"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["df5289c7-8630-4aa7-9416-3c7291351ec1"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Ortheus BrowRing R"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["31d2d85f-2937-49da-b6b4-20387164fe6a"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Ortheus Earring L"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["c069232e-c9e8-40af-b5e0-26d458baeb07"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Ortheus Earring R"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["9e43077a-a375-4175-90e8-986e03cade91"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Ortheus HelixRing L"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["17b22855-afa5-4cd4-af47-20621e2dcbc1"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Ortheus HelixRing R"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["8e460930-875f-4aac-b3f7-2506a677ff67"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bald"                          , IntendedRace = "None"      , Description = "", }
baseGameOptions["fbe4fed5-a904-4a6d-8e85-81c7e2272a95"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Rover's Tumble"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["ce296839-ccf2-4183-8588-a8b86845e3c2"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Mongoose Tail"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["03bb366d-e3da-4976-9dab-c7635965f330"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Luskan Plume"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["2db044c9-cc4e-4de2-8c7e-9b57273b2dfe"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bakery Buns"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["bf42de20-4e5f-4d5c-b05b-09fa19c3f6a4"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Trobairitz Knot"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["c1e46990-cc88-47d0-86cd-68bf37b75f34"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Orcscrews"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["f16f9197-6a56-42d9-9d63-68058e416d55"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Lone Wolf Bun"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["f9fe5d9b-df50-4289-8794-cef219d2c8a5"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Feywild Trickster"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["0e07530b-4b7c-46d2-a86a-cc02e9970100"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Solemn Huntress"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["091ec534-da79-4e35-8161-5b4720102fb1"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Knife Honed"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["bf741bc0-5908-451c-aede-634c976bc669"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Pincer Movement"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["8e696e3e-28d0-4c2e-b2d7-d911cb712949"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Springtime Entanglement"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["19102038-19cf-46f5-8749-1d1e33176957"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Carrion Feathers"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["d7a10a5a-a505-48cd-9d49-4424fe2177b5"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Gorgon"                        , IntendedRace = "None"      , Description = "", }
baseGameOptions["9ec38066-ac6f-4661-a9c9-c07a3afb5d9b"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bruenor Braids"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["6fce31da-4209-426c-9175-374df35202b8"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Neverwinter Scarf"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["e45af05e-9e93-4fa7-92b6-eea5a4b08f1b"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Duster"                        , IntendedRace = "None"      , Description = "", }
baseGameOptions["9cc182e7-8a73-44e4-835e-d55b89d139fc"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bone Dance Braids"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["0fe24092-90c1-43c1-b991-96ca465c14d8"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Duchess Coronet"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["cd480bbf-02a2-496c-a1ca-785ae04b2edd"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Wildcat"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["c8491f2a-f1e4-4b79-93cc-27893098fb95"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Seashell Garden"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["49bace97-81de-4868-9bfa-23fc27f3ebc2"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Dryad"                         , IntendedRace = "None"      , Description = "", }
baseGameOptions["c4de3fe0-0f5c-4315-86b8-33b721dbe0ad"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Furled Wings"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["c6c4f0cb-d9db-4501-8222-1af90631a022"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Ramhorn Cascade"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["dbfbdf4c-0622-4413-87ea-114c4c2b0e56"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Portrait Model"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["73a751ec-1ce9-4e67-9e1d-e95f4bac8ce4"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Dewdrop"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["2b4d2522-7ccb-426d-9892-bffe0ad6aaad"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Derlusk Sojourn"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["d40d509a-07a6-4aaf-b975-718ec13d6c5e"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bohemian"                      , IntendedRace = "None"      , Description = "", }
baseGameOptions["925022e4-564e-407d-88e0-9cf9fe0633c7"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Academy Dropout"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["8faab795-617f-4aca-9180-ac97abc5fcef"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Mythmaker"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["48ed6d25-7734-424e-827b-ac3ee0fbde3f"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bramble Thicket"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["aff5aa8e-757e-4151-b5bb-3ccbedc114e0"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Fence Board Shavings"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["5ba51519-5c23-4a9c-8329-f6bcac4d4d63"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Sensible Extravagance"         , IntendedRace = "None"      , Description = "", }
baseGameOptions["ce324e38-6463-4594-a713-3781ce365bb2"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Cauldron Foam"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["e0f3937c-081a-4b8d-843b-d090b112309e"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Dandelion"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["a35cbe20-7a31-47b7-bc1f-9b6ebfb8106a"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Loomspun"                      , IntendedRace = "None"      , Description = "", }
baseGameOptions["3b7604f1-8a3e-45e3-820c-5ed77fbb2eaa"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Peeress"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["f48fead3-8a9c-425e-9ae0-00d15f4f7d8f"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Windblown"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["97d373a4-75fa-4484-8cf2-5dba5b444615"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Valiant Heart"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["d6039e79-5cb1-4d38-b7c2-ebfb07980de2"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Kwahom"                        , IntendedRace = "None"      , Description = "", }
baseGameOptions["85187a87-fdfd-4a4c-ac95-a47906976662"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Arabel Ribbon"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["ad4c2c6d-e451-410c-8ca8-5726400779ca"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Languid Bandit"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["c87988bb-90ef-4478-b5fb-042489608369"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Moonshae Cap"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["0947bbdf-ca18-4ec8-be7a-5181fdbe5671"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "River Shaman"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["3191a567-fbec-4c40-bc5e-4abae2253b5f"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Waterdavian Scholar"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["6100c90e-061d-4bf7-b0ef-de22ee46587a"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Wavelet"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["9fe21148-9af2-462a-9678-f04d309b4b8d"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Savant"                        , IntendedRace = "None"      , Description = "", }
baseGameOptions["0966c115-f522-40d6-b5cc-a331af60879d"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Highbrow Low Moralist"         , IntendedRace = "None"      , Description = "", }
baseGameOptions["c8b3365d-c442-45c9-9830-f5aaf18d0a9b"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bonbons"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["62d77ee2-38cf-4c17-b093-9511b5e37b8b"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Sorcha Curls"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["48a84bab-e178-47a7-b5a3-6d92a6c9cdd7"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Eyrie Peak"                    , IntendedRace = "None"      , Description = "", }
baseGameOptions["72446580-6a6a-4f76-a69a-9e9e6ab9e4cb"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Conqueror"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["6f8806e6-183f-4286-b09e-abc7d6c00f18"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Knave Braid"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["2768eb7b-abb5-47cd-92bc-e4a8caf2521a"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Fair Forester"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["46d35c27-662d-426c-910a-e4cb46e82698"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Chrysalis Pod"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["4aac9b41-75f7-4724-b3cd-e6ca810092a7"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bardic Inspiration"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["18c89719-e482-4d35-b12b-189200b58e72"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Topknot"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["63bf0f22-2fed-4e7d-a010-df302d116c99"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Tidy Mohawk"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["d771f181-d0d3-4f4f-bd25-6ce1d43c9ef4"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Piranha Tooth Mohawk"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["bb02e15a-84f5-4120-8542-a68eac3cf04d"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Poppy Bud"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["1e4f490f-5268-4543-bd71-4be3d98ef5bb"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Rapscallion"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["806a9207-3460-403b-b7de-4f2fea72f107"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Orchestra Wings"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["38b85a31-326a-477b-943c-84adaebe1933"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Elysium Fan"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["0a2d2764-c19f-40cd-b6f8-35ce8a7716d7"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Twisted Sinister"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["a965f501-2553-4788-9b22-9a4f1d6264f7"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Maudlin Pixie"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["80e898ba-34da-42ee-b3a7-007a34cfc9e9"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Faerûn Fantasia"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["85d21f25-eba4-40a0-ab95-17524aed7715"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Partial Eclipse"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["188ac040-feee-4850-a4e2-8266df8840a7"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bone Dance Braids"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["a58426fc-efc5-446f-a679-f16af43a5bfc"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Duchess Coronet"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["5240e3c3-070a-40f8-acdb-d1bc59651389"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Seashell Garden"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["42cf8205-f644-463d-9729-7f2c05e6b3c3"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bakery Buns"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["b67bf2f2-1743-42e4-ae12-ecbd9ccc0341"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Orcscrews"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["c82fb8ad-6de5-453f-bc3c-a1e43c65913f"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Feywild Trickster"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["caa981f1-2a31-4f1c-b8e8-767f00bc15ca"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Solemn Huntress"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["1c4e8a79-6814-4ca3-a1aa-c153325f3225"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Mythmaker"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["17adcecb-f9ae-4b86-9233-86d8da452ed6"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Cauldron Foam"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["be10983e-4571-44e2-ab4b-cc201b494581"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Dandelion"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["8ac4dc21-3495-48f5-bfd5-27f2fbb1b577"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bramble Thicket"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["710b3b99-1f32-48af-b8e9-63cefbb25d2f"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Fence Board Shavings"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["906fe2e4-6d20-4b8a-844a-66c0005cc9fa"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Loomspun"                      , IntendedRace = "None"      , Description = "", }
baseGameOptions["cb246058-ef27-4ef9-844c-4d322805d05e"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Orchestra Wings"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["da356348-08d6-492e-abc4-95d30a29df54"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Peeress"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["c9d01af4-ec55-4a51-b543-3c8c6cebe39b"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Windblown"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["82ec3f7c-1333-43e9-a1f5-ba7004ff20b2"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Valiant Heart"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["11be7ce8-765e-4121-bb2f-577598b378f4"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Kwahom"                        , IntendedRace = "None"      , Description = "", }
baseGameOptions["d66fb752-43e0-454d-871b-1493604e732b"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Arabel Ribbon"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["aea10983-bf9a-4104-8e25-2e11873a611e"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Languid Bandit"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["b5dca54f-a7d1-4680-bf66-88285bff4ac8"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Moonshae Cap"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["06fd7aa0-6276-41d1-ac18-f145ab9c12e3"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Rapscallion"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["fe201a29-94b8-43b6-b0d4-297b4e8fefca"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Piranha Tooth Mohawk"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["a9e72193-289f-4193-93ed-9b587ded4fc4"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Tidy Mohawk"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["03d9e6e2-7c76-40a7-8203-c3f13e8ba4ec"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Topknot"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["fc7fab43-2e98-4eb3-b03a-9afde9237058"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Twisted Sinister"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["7eded165-99f0-4229-98df-b8f87863092c"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Knave Braid"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["fc919690-b099-4421-9c64-760f43214677"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Lone Wolf Bun"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["94077779-c310-432d-a6df-132193a5ddd7"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Knife Honed"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["03f51dd3-d2b2-4cb6-891b-6bd2068b5262"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Springtime Entanglement"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["a028b670-b253-4029-b248-9c8fd8a3edb4"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Sensible Extravagance"         , IntendedRace = "None"      , Description = "", }
baseGameOptions["51cf1f1d-aecc-42b6-81cd-c4189ae0ae15"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Elysium Fan"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["d5cf9202-9df7-41a3-b791-d8ee6faa8811"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Savant"                        , IntendedRace = "None"      , Description = "", }
baseGameOptions["429f0b9c-7c15-4c22-bfc8-5dcea83a6fbd"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Maudlin Pixie"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["d9ee080c-8081-4b15-9dd1-5a14e55e1bfb"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Highbrow Low Moralist"         , IntendedRace = "None"      , Description = "", }
baseGameOptions["95484658-85c0-4cc2-8f17-5fb47e62b0bc"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bonbons"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["0bc42c93-88c2-40b6-983f-05f7248c7942"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Eyrie Peak"                    , IntendedRace = "None"      , Description = "", }
baseGameOptions["7a10b46d-5f16-4229-a274-818b843009f6"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Gorgon"                        , IntendedRace = "None"      , Description = "", }
baseGameOptions["6905415f-f679-4872-81ac-543943e8c432"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Ramhorn Cascade"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["b4c8cb97-c6cd-47e2-815e-cfa986e28931"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Rover's Tumble"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["8b981705-a203-40d0-b14b-346fdcd42f5d"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Trobairitz Knot"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["dc1cbb6f-1039-4b7d-9349-983dfbac0737"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Carrion Feathers"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["2ab6ff4e-ef23-4413-89a4-63109cd959b5"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Derlusk Sojourn"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["6d295f08-b737-4876-be14-32f29374d4c6"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Academy Dropout"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["7b94976b-812c-4150-950b-7771653f566c"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Conqueror"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["0a6b3493-1c22-4bca-8cb1-1894d0103b81"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Chrysalis Pod"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["95692941-6bf6-4b09-923f-35ec5b72850f"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "River Shaman"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["a0d1f7d5-c738-4493-82ba-2eff447a6a40"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Waterdavian Scholar"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["2718535d-1459-417e-83a0-de5fa41efb06"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Wavelet"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["33d95001-ef28-48d6-9547-140661da8684"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Sorcha Curls"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["6981bb93-be25-44c9-b77f-1069d971e339"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Untied Parcel"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["e68867fd-684f-4ba3-acfa-98a046c00934"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Neverwinter Scarf"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["75ca655b-9dd6-4a5f-a3d7-a3584128698b"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Wildcat_D"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["0c719f93-d3ac-43dd-895d-b76c194f3546"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Furled Wings"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["8bf9c188-84c4-457b-9d19-6b0bfef3f000"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bruenor Braids"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["dd2c4ca5-557e-4608-9edb-f10695415ef5"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Fair Forester"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["a79e6af1-110f-4fab-9377-3dcb2d02ab4a"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bardic Inspiration"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["254a87f7-1824-4ae1-b0bc-c372bac8f8ed"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Duster"                        , IntendedRace = "None"      , Description = "", }
baseGameOptions["718b0071-19b8-4e07-8785-f276deaf7af5"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Mongoose Tail"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["9a3185c2-975b-4ad4-bc9a-c74e8642679d"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Luskan Plume"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["27b97d46-6703-470d-a38f-90b449b05009"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Dewdrop"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["8903c098-11f0-4f11-9226-4073ff1db0ef"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Precision Bolt"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["505475c9-cda2-4067-bc8e-b95e4322203b"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Precision Bolt"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["2c5ded20-5dc0-40d2-93cd-e26fd2f43c90"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Gemstone Droplet"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["731222a1-bd83-49b4-86c3-51d2ce369cb9"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Gemstone Droplet"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["97ec9973-3c3a-4df1-adf0-4636a6cb03bb"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Bladebangs"                    , IntendedRace = "None"      , Description = "", }
baseGameOptions["1ecdfd46-ebb6-45bd-995f-d5c2fd79ec21"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Pincer Movement"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["2fec8141-eb41-49f2-bf52-21693176bc48"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Ballerina Bun"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["680c9011-f727-48d8-bdaf-aba7667c9861"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Interplanar Braids"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["a8384c39-bb03-4a5e-80c5-b7b4062c5ee9"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Braided Bunches"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["2fe0cab2-ab4b-4fad-b4a3-d4c16efa3ef3"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Layered Lob"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["3565c8c7-63c2-49df-8922-8b1b96fd0ed7"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Windswept"                     , IntendedRace = "None"      , Description = "", }
baseGameOptions["503c74e6-0860-4eed-80ea-1fe0e5ffa45a"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Will O'Wisp"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["e15cdc99-71e9-484a-87de-c845452c8a55"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Pinned And Perfect"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["9c890576-1ede-4de2-bf56-a8b53616bf73"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Veiled Evocation"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["8231239f-2dcd-477e-8b23-86dab0f4318f"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 1 Brow 1"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["d4346eaa-656d-4ff4-8382-f940faa92965"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 1 Brow 2"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["840aac96-fc21-4f7a-95e0-bbdd99f2e8fd"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 1 Lobe"                    , IntendedRace = "None"      , Description = "", }
baseGameOptions["a5c9175c-a997-4792-a606-64b9a2774c5b"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 1 Lobe"                    , IntendedRace = "None"      , Description = "", }
baseGameOptions["5bd77841-bbdc-4e2b-88a3-b22fc74fdf46"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 1 Brow A L"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["29a1a696-81b6-4d4a-8b3a-38f652fa74d6"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 1 Brow B R"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["00b16dba-2ce6-439b-bbff-b71e97f85143"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 1 Brow B L"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["a7f42b00-7f14-4137-8665-5bbe986b1bdf"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 2 Chain Lobe L"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["0311cf7a-3fa4-4b05-a608-4716d54c36a4"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 2 Chain Lobe R"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["dcdb8ef2-fa72-475e-9e21-d8b953c42522"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 2 Chain Bridge L"      , IntendedRace = "None"      , Description = "", }
baseGameOptions["28806ed1-6301-4836-bf39-779122ec0b84"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 2 Chain Bridge R"      , IntendedRace = "None"      , Description = "", }
baseGameOptions["c3eb8b5e-b5eb-4b50-9c49-058e74439656"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 2 Ring C Helix b L"        , IntendedRace = "None"      , Description = "", }
baseGameOptions["b647514a-04f7-4be4-a3a3-e7f9d786e303"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 3 Swirl Lobe L"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["adcde0f3-3f4e-4e03-8e21-5685e3723bbf"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 3 Swirl Lobe R"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["2a0a3dbe-630e-4605-8305-339eb41c6ad6"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 3 Swirl Nostril A R"   , IntendedRace = "None"      , Description = "", }
baseGameOptions["1721a058-0e06-471d-845d-7305ca88f44f"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 3 Brow A L"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["5c9bc416-de0d-4d6f-8be4-24beaf0099e4"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 3 Brow A R"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["ba42b168-d64c-4101-bc5d-3ae77bb93eb3"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 3 ring helix  A L"         , IntendedRace = "None"      , Description = "", }
baseGameOptions["045a5fc3-1b43-403d-afe4-efc8faaa082a"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 3 ring helix  B L"         , IntendedRace = "None"      , Description = "", }
baseGameOptions["35b7f0c1-1ed0-4303-b90a-a1f4066b4523"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 3 ring helix  B R"         , IntendedRace = "None"      , Description = "", }
baseGameOptions["ab6e3f94-c481-4cd4-8e01-d7d42f8b0579"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 3 Nostril A R"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["61114808-3287-4698-b738-d94b76a8642d"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 3 Brow Stud A L"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["9b5e310c-56e7-4ab7-9e4d-10979e16080c"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 3 Brow Stud A R"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["80621714-648f-4cf9-8d30-a75829b1b56b"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 3 Targus Stud A L"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["6ac21e68-b88d-4ea0-baa3-310872e4fdca"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 3 Targus Stud A R"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["32df873d-fab9-4dc7-8d2f-a253074106e1"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 4 Bird Lobe L"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["3e5e346b-8383-4fdf-aa8a-fecabe96dcbd"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 4 Stud Spike D L"      , IntendedRace = "None"      , Description = "", }
baseGameOptions["b87261e6-c8b6-4ebe-bd92-978747f89467"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 4 Stud C L"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["c0e2e696-5363-45a0-bca9-e75f927a49f2"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 4 Stud Spike D R"      , IntendedRace = "None"      , Description = "", }
baseGameOptions["476d4243-a4ba-4f25-8d2e-39bb95294ac9"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 4 Stud C R"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["0f9151e8-c340-4f02-a87e-4ea8947f9511"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 4 Bird Lobe R"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["eec50709-cbc4-4186-825b-3021d6921ff5"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 4 Ring Helix R"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["bfce578e-87ae-46ea-83ce-590bf0d08af8"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 5 barbell brow"            , IntendedRace = "None"      , Description = "", }
baseGameOptions["4a903b20-bf4a-4246-b134-3b8e5367ba07"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 5 Nostril R"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["3b62f841-3d63-442b-98eb-1d013572f5f1"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 5 Ring Lobe A L"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["ef0c9b0c-591f-4d76-86e1-454c71cac2d8"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 5 Ring Lobe A R"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["e9cdfcd5-3e91-436a-b532-c8fae22136d0"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 5 Helix A R"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["da6968d9-5721-43a7-ac2a-282db7faf575"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 5 Helix B R"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["8361d543-3b97-4349-970c-57f5c4d75d82"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 5 Nostril L"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["dc2af94b-d7dd-4f5f-bf6f-eb009ca46eb4"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 5 Ring Septum A M"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["aefc6007-6c2c-478b-b49f-05c62c46605e"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 5 Stud Targus A R"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["8a485f4f-e026-446a-8b2f-2609930b7002"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 5 Stud Brow A L"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["dbf8f0a8-34d4-4167-b404-5037ecff750c"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 5 Stud Brow A R"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["10d762d6-735c-4303-8ab6-640091c463ca"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 5 Stud Brow B L"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["5250c19b-dc53-499c-b253-3909b2ad2ec8"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 5 Stud Brow B R"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["fb31019d-6572-410b-8129-3f373f9ffaa2"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 5 Stud Lowlip A L"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["512b737d-8413-4db5-8219-81552974fc50"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 5 Stud Lowlip A R"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["57cb958c-b027-4941-856c-dd0961ee6478"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 5 Stud Lowlip B L"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["95c96519-bda7-43a7-9007-048e4a424fcf"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 5 Stud Lowlip B R"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["a67aa85d-7c65-42c2-ba5a-9f048a28a8f8"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 6 Tusk Lobe L"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["36361726-8bdf-4dc0-ae64-a31de980b6aa"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 6 Tusk Lobe R"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["0060e6d7-0034-4b13-85b3-0ed935440a40"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 6 Tusk Bridge R"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["901fb5ae-b95b-49f8-919b-61c7caf261c4"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 6 Tusk Bridge R"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["9876a6ee-6eea-4082-97cf-29b0f13d92cf"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 6 Moon Brow"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["df67fae5-0c76-4ba7-9f28-7a4cec6d7c43"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 7 Stud Lobe L"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["d14e50a1-fbc5-4cac-97d6-a6c6b9599e07"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 7 Stud Brow B L"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["05ed7b15-58b0-44cf-a6f1-a0b483d6fc3a"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 7 Stud Uplip A L"      , IntendedRace = "None"      , Description = "", }
baseGameOptions["441478ef-a5e4-4c71-a6f2-949971bec216"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 7 Stud Uplip B L"      , IntendedRace = "None"      , Description = "", }
baseGameOptions["5dd295f5-092a-4a7c-a882-a053cef616e3"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 7 Stud Uplip C L"      , IntendedRace = "None"      , Description = "", }
baseGameOptions["9f089afe-c341-4451-8cd9-dc424f5fba2f"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 7 Stud Lobe R"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["35c948fb-543f-425b-bc82-173c73fd5c6b"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 7 Stud Bridge R"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["b717902f-0391-45a0-922b-135653bde992"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 7 Stud Brow B R"       , IntendedRace = "None"      , Description = "", }
baseGameOptions["0f4d04a3-2b52-4261-a19b-90d376fb128c"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 7 Stud Uplip A R"      , IntendedRace = "None"      , Description = "", }
baseGameOptions["dc77ec8d-5f0c-4627-88ae-cae3ef09bab0"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 7 Stud Uplip B R"      , IntendedRace = "None"      , Description = "", }
baseGameOptions["45fcc7a1-4df9-498b-97a3-d2a52a21bbee"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 8 Tail Lobe L"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["4c8ae2fb-492d-4023-98d6-2c04ce0773ce"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 8 Lowlip D L"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["172524be-a6cc-4204-b664-1d14b0a4ee62"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 8 Tail Lobe R"             , IntendedRace = "None"      , Description = "", }
baseGameOptions["2202eb26-b7dc-4fcd-8f38-61722e91a7b6"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 8 Lowlip D R"          , IntendedRace = "None"      , Description = "", }
baseGameOptions["33fb7410-0373-44ce-8652-4a213e1dc470"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 9 Sword L"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["0c4dac1e-abe7-4dec-993a-1cbf73fe01e0"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 9 Stud Lowlip A L"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["ec5a0b32-ba02-4008-994f-6deebf75670b"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 9 Stud Lowlip B L"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["50489c12-4668-42b4-b625-831c303e0977"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 9 Stud Lowlip A R"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["907aa98e-7a5a-4634-bcb2-f498b6ed5a1b"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 9 Stud Lowlip B R"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["00e10b03-0f21-42f6-9b1c-cd1de83dd657"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 9 Ring Nostril A L"    , IntendedRace = "None"      , Description = "", }
baseGameOptions["38be22d9-9dad-45a0-a38a-e8ccc8ba1f4e"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 9 Sword R"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["c2797414-c4c8-4898-92b0-0c7a09ac3bda"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 9 Tusk A R"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["573f4b09-308a-45af-b18e-6f8668af0ea2"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 9 Tusk B R"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["33167c69-56b3-463b-92ae-b57e02476bf8"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 10 Lobe A L"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["46b34e71-1e91-48c2-81e7-8cb1532fbbb7"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 10 Lobe A R"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["f56063f5-e095-4687-b09a-ecfa12c3c8ec"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 10 Helix A L"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["5bf9050a-4c43-4847-ae89-10b7b20a95dd"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 10 Helix B L"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["fd57b4cc-98c4-40c4-91dc-ede0267ccdfd"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 10 Lobe B R"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["b53c1e5f-e000-45ae-82f2-e5c28b5676be"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 10 Tragus L"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["04e1515b-65b3-4994-a383-f3fb3e49cc54"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 10 Tragus R"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["ae47ccc7-bf63-4c1a-a289-132ad0d36d90"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 10 Spike Brow A L"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["15f5ae8b-80b2-4a5f-a384-85ac12f14605"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 10 Spike Brow A R"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["59ecc224-85a3-44a8-9bbf-ec7816e2a5a1"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 10 Spike Brow B L"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["4e57d0e0-5dde-4894-bc81-b72ab51506ea"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 10 Spike Brow B R"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["dedadbce-2fec-41eb-940b-5e62cb083cf3"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 10 Spike Targus A R"   , IntendedRace = "None"      , Description = "", }
baseGameOptions["3b2cf8a0-dec0-4398-b6fb-c48b10a76e90"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 10 Spike Targus A L"   , IntendedRace = "None"      , Description = "", }
baseGameOptions["28dbcf69-0250-465b-bc3d-3fc1723e2ebb"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 10 Stud Lowlip A R"    , IntendedRace = "None"      , Description = "", }
baseGameOptions["cf1e93df-7243-4df5-a8f3-7f8c4a9246d1"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 10 Stud Lowlip B R"    , IntendedRace = "None"      , Description = "", }
baseGameOptions["54e9412c-6f4e-4d17-9e24-49d8633eb22c"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 10 Stud Lowlip B L"    , IntendedRace = "None"      , Description = "", }
baseGameOptions["c84ed6bb-f3d3-4d8f-b9c2-2812f0dcd111"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 11 Nose ring"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["b84feeae-9069-4974-bbb2-5f07f1e39fbc"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 11 Nose ring R"        , IntendedRace = "None"      , Description = "", }
baseGameOptions["46f339ee-f5ee-460e-9526-9d0884d9926c"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 12 lobe L"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["d12af7cf-c29a-4ed9-ba44-6f694f4e04d5"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 12 lobe R"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["1011dd8f-15bd-4bc3-a69d-c98a9ac5ba7a"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 12 Brow B R"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["4d1f12a6-87e2-4911-8f91-83a7223ee34c"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 12 Stud Uplip A R"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["92a17c1a-905d-4009-b376-82604deb5389"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 12 Stud Uplip A L"     , IntendedRace = "None"      , Description = "", }
baseGameOptions["dc9e3db3-479c-4fd5-82a4-997a1d5b5e6c"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 12 Brow L"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["870f197a-54dd-4aac-ab32-b21ca66e832f"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 13 Lobe L"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["8036c562-421a-4daa-80ac-919ba270d109"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 13 Bridge L"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["75c9dcff-62e6-41b8-bac4-42be78e96913"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 13 Lobe R"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["6aa6b4ee-ffb2-4f2f-a3a7-40bd15bf5633"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "DGB Set 13 Bridge R"           , IntendedRace = "None"      , Description = "", }
baseGameOptions["6f48e794-f5c9-4259-b9e6-f4f3828ed8cc"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Plucky Fable"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["232682d3-fa7a-446d-8c90-16d339b69538"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Scooped Cèilidh"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["534c9aae-ea86-4d70-9dda-2fcabf8e214c"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Busy Promenade"                , IntendedRace = "None"      , Description = "", }
baseGameOptions["f53900f4-7980-457c-bc80-cd78971af9c3"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Foxtail"                       , IntendedRace = "None"      , Description = "", }
baseGameOptions["b4ce515f-63a8-4ac6-99e0-a2a428afc0a9"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Hubris"                        , IntendedRace = "None"      , Description = "", }
baseGameOptions["1b97c610-4d83-4ac7-a9e4-4304b6d67fd6"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Willow Tears"                  , IntendedRace = "None"      , Description = "", }
baseGameOptions["719bedca-db3f-4b3f-8ed1-afc3acd9ff21"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Immortality"                   , IntendedRace = "None"      , Description = "", }
baseGameOptions["d0db23d3-83e9-4383-a51d-f408091a2aa6"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Flaunting Bounce"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["117aab50-73fb-464d-9af7-82bcebc7606d"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Innkeep Braid"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["086bfc03-927c-43ce-a818-3db3b8ba80ab"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 14 septum"                 , IntendedRace = "None"      , Description = "", }
baseGameOptions["427012ca-9b18-424c-8ee9-a59ff55b152e"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 15 L Helix A"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["79ae4309-bd93-4620-b0d6-a80bb7e7e8a4"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 15 L Helix B"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["3248f9d5-05cc-42f8-a111-772f894439a7"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 15 L Lobe A"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["e4998190-4621-4de6-a49b-8e43d751c074"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 15 R Helix A"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["be72fe8d-a81a-4459-a637-344f4e508ac7"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 15 R Helix B"              , IntendedRace = "None"      , Description = "", }
baseGameOptions["43e7eb3d-ca85-42b9-b32d-ad1be18d1001"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 15 R Lobe A"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["514dcb13-e15f-4cb0-94a2-cf22d9cf2965"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 15 L Lobe B"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["ae1ce151-6944-435a-a616-30c4d59bfb31"] = { SlotName = "Piercing"      , BodyType = "None" , BodyShape = "None"  , Name = "Set 15 R Lobe B"               , IntendedRace = "None"      , Description = "", }

-- END Generated Entries: output_0_CharacterCreationSharedVisuals_from_CharacterCreationSharedVisuals.lua

-- BEGIN Generated Entries: output_1_CharacterCreationSharedVisuals_from_CharacterCreationSharedVisuals.lua

baseGameOptions["e05b0f79-d3af-41eb-b0b2-1164b6f0debf"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Shar Wrath Hair"               , IntendedRace = "None"      , Description = "", }
baseGameOptions["c7f78eb7-6858-4f02-836b-d8c8b56c34fc"] = { SlotName = "Hair"          , BodyType = "None" , BodyShape = "None"  , Name = "Nightsong Fate Hair"           , IntendedRace = "None"      , Description = "", }

-- END Generated Entries: output_1_CharacterCreationSharedVisuals_from_CharacterCreationSharedVisuals.lua



local sourceAddonKey = "BG3-DAF-CCSV"

for k,v in pairs(baseGameOptions) do
    local optionUUID = k
    local categoryKey = v.SlotName
    local optionDesc = v.Name -- TODO
    local bodyType = v.BodyType
    local bodyShape = v.BodyShape
    local intendedRace = v.IntendedRace

    local name_no_spaces = string.gsub(v.Name, "%s+", "_")
    local bodyType_char1 = string.sub(bodyType, 1, 1)
    local bodyShape_char1 = string.sub(bodyShape, 1, 1)
    if bodyShape == "Normal" then
        bodyShape_char1 = ""
    end
    local optionKey = string.format("%s_%s_%s%s", intendedRace, name_no_spaces, bodyType_char1, bodyShape_char1)

    VisualLibrary.AddOptionWithCompatInfo(sourceAddonKey, categoryKey, optionKey, optionDesc, optionUUID, bodyType, bodyShape, intendedRace)
end
